[package]
name = "nano-mesh"
version = "0.0.1"
authors = ["Yevhen Shevchenko (boshtannik) <boshtannik@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "nano_mesh"
test = false
bench = false
path = "src/main.rs"

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.1.0"
nb = "0.1.2"
heapless = { version = "0.7.0", features = ["serde", "ufmt-impl"] }
avr-device = "0.5.1"
embedded-hal = "0.2.7"
platform-millis = { git = "https://github.com/boshtannik/platform-millis.git" }
platform-millis-arduino-nano = { git = "https://github.com/boshtannik/platform-millis-arduino-nano.git" }
platform-serial = { path = "../platform-serial" }
platform-serial-arduino-nano = { path = "../platform-serial-arduino-nano" }

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "7dfa6d322b9df98b2d98afe0e14a97afe0187ac1"
features = ["arduino-nano"]

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[features]
serial_debug = []
# default = ["serial_debug"]
